version: 2.1

references:
  workspace: &workspace
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace

executors:
  node:
    docker:
      - image: circleci/node:10.16.3
    working_directory: *workspace

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - persist_to_workspace:
          root: *workspace
          paths:
            - "*"
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      
  test:
    executor: node
    steps:
      - *attach_workspace
      - run: npm test

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
